---

# Main tasks file for mariadb-server role

- name: Load the OS specific varibles
  include_vars: "{{ role_path }}/vars/{{ ansible_distribution | lower }}.yml"


- include: "{{ item }}"
  with_items:
    - "{{ role_path }}/tasks/install_{{ ansible_distribution | lower }}.yml"
  tags:
    - install
    - mariadb-server


# Configure mariadb
- include: configure.yml
  tags:
    - config
    - mariadb-server


# Manage accounts
- include: manage_accounts.yml
  tags:
    - config
    - mariadb-server

